{{- if .Values.vault.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.vault.secretName }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: {{ .Values.vault.secretName }}
    creationPolicy: Owner
  data:
    {{- range .Values.vault.secretKeys }}
    - secretKey: {{ . }}
      remoteRef:
        key: {{ $.Values.vault.remotePath | replace "secret/data/" "" | quote }}
        property: {{ . }}
    {{- end }}
{{- end }}
