apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sound-bot.fullname" . }}
  labels:
    {{- include "sound-bot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "sound-bot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sound-bot.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | toString }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - secretRef:
                name: {{ include "sound-bot.fullname" . }}-app-secrets
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 40
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
