apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sound-bot.fullname" . }}
  labels:
    {{- include "sound-bot.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "sound-bot.fullname" . }}-secret-creator
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "patch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sound-bot.fullname" . }}-secret-creator-binding
subjects:
- kind: ServiceAccount
  name: {{ include "sound-bot.fullname" . }}
roleRef:
  kind: Role
  name: {{ include "sound-bot.fullname" . }}-secret-creator
  apiGroup: rbac.authorization.k8s.io
