{{- if .Values.sso.vault.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "argocd-infra.fullname" . }}-sso
  labels:
    {{- include "argocd-infra.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: argocd-secret
    creationPolicy: Merge
  data:
    {{- range .Values.sso.vault.secretKeys }}
    - secretKey: {{ . }}
      remoteRef:
        key: {{ $.Values.sso.vault.remotePath | replace "secret/data/" "" | quote }}
        property: {{ . }}
    {{- end }}
{{- end }}
