{{- if .Values.sso.vault.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  labels:
    {{- include "argocd-infra.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.sso.vault.server | quote }}
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: {{ .Values.sso.vault.role | quote }}
          serviceAccountRef:
            name: {{ include "argocd-infra.fullname" . }}-vault
{{- end }}
