{{- if .Values.sso.vault.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "argocd-infra.fullname" . }}-vault
  labels:
    {{- include "argocd-infra.labels" . | nindent 4 }}
{{- end }}
