apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sound-bot
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/aeonamind/gitops.git
    targetRevision: HEAD
    path: infra/sound-bot
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
