argo-cd:
  global:
    domain: argocd.eugenebox.uk

  configs:
    cm:
      url: https://argocd.eugenebox.uk
      admin.enabled: "true"
    params:
      server.insecure: true

  server:
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - argocd.eugenebox.uk
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web
    extraArgs:
      - --insecure
