apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 7.1.0
    helm:
      values: |
        server:
          extraArgs:
            - --insecure
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - argocd.eugenebox.uk
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: web
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
